# Generated by Django 4.2.6 on 2023-11-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='items',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
