# Generated by Django 4.2.6 on 2023-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cartitems_items_cartitems_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='items',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
