# Generated by Django 4.2.6 on 2023-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cartitems_items_alter_cartitems_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='items',
            field=models.IntegerField(null=True),
        ),
    ]
