# Generated by Django 4.2.6 on 2023-11-18 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(upload_to='banner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
