# Generated by Django 4.2.6 on 2023-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_items',
            field=models.IntegerField(default=1),
        ),
    ]
